### ISSUE TITLE
Support multiple chunks in label

### ISSUE THREAD

**Issue by jakirkham** [dask-image/dask-ndmeasure#58]
The current implementation of `label` in PR ( https://github.com/dask-image/dask-ndmeasure/pull/57 ) does not support multiple chunks, but only 1 chunk along all dimensions. This is still useful when working with individual images that fit in memory. Still to better utilize compute resources and to extend to even larger data, it would be nice to be able to support multiple chunks.

**Comment by kmader** [comment]
Without supporting multiple chunks the function is just a delayed wrapper on ```scipy.ndimage.label```, an easier starting point might be something that just does approximate labels and returns the label run indepndently on each chunk

**Comment by jakirkham** [comment]
Good point! I think this is a consequence of `dask.delayed`'s behavior, which is to consolidate chunks. We might consider moving to `map_blocks` and doing the `rechunk`ing ourselves, which may be a bit nicer from an end user perspective.

Ultimately it is true that `label` as it stands now is not very exciting. For most of the data that we have been using this on thus far, the frames themselves fit in memory, but there may be too many of them to feed all of the frames into `scipy.ndimage.label`. In this way, `label` as it exists now solves a real world problem.

However this is not what one thinks of when they think of an out-of-core labeling function. A better solution likely involves [`da.map_overlap`]( http://dask.pydata.org/en/latest/array-ghost.html#dask.array.map_overlap ) or similar. What's not clear to me is how we handle this joining of labels across block boundaries (particularly if they cross over multiple block boundaries). Maybe you have thoughts on this?

**Comment by kmader** [comment]
It is a nightmarish problem to cover all of the possible edge cases and try and be somewhat efficient. I guess it would be good to try and figure out the most common use cases and make it work reasonably well for them.

## Objects << Chunks (Cells in pathology slices)
`da.map_overlap` with an additional step to delete objects on border or where the midpoint is on the. border

## Objects >> Chunks (vessels in full body scan)
- downsample image onto one node, label and then upscale labels to chunks

**Comment by jakirkham** [comment]
This issue was moved to dask/dask-image#29
